##########
## Data Set information
##########
weather.info <- list()

## List units for reference later
weather.info[["units"]] <- list() 
weather.info[["units"]]["DATE_TIME"] <- "GMT"
weather.info[["units"]]["DIR"] <- "Compass Degrees"
weather.info[["units"]]["SPD"] <- "MPH"
weather.info[["units"]]["GUS"] <- "MPH"
weather.info[["units"]]["CLG"] <- "Hundreds of Feet"
weather.info[["units"]]["VSB"] <- "Statute Miles"
weather.info[["units"]]["TEMP"] <- "degrees F"
weather.info[["units"]]["DEWP"] <- "degrees F"
weather.info[["units"]]["SLP"] <- "Mb"
weather.info[["units"]]["ALT"] <- "inches"
weather.info[["units"]]["STP"] <- "Mb"
weather.info[["units"]]["MAX"] <- "degrees F"
weather.info[["units"]]["MIN"] <- "degrees F"
weather.info[["units"]]["PCP01"] <- "inches"
weather.info[["units"]]["PCP06"] <- "inches"
weather.info[["units"]]["PCP24"] <- "inches"
weather.info[["units"]]["PCPXX"] <- "inches"
weather.info[["units"]]["SD"] <- "inches"

## List variable descriptions for comprehension later
weather.info[["Description"]] <- list()
weather.info[["Description"]]["USAF"] <- "AF Catalog Station ID Number"
weather.info[["Description"]]["WBAN"] <- "NCDC WBAN ID Number"
weather.info[["Description"]]["DATE_TIME"] <- "Date in GMT"
weather.info[["Description"]]["DIR"] <- "Wind Direction in compass degrees"
weather.info[["Description"]]["SPD"] <- "Wind Speed in MPH"
weather.info[["Description"]]["GUS"] <- "Gust Speed in MPH"
weather.info[["Description"]]["CLG"] <- "Cloud ceiling w/ 5/8ths+ coverage in hundreds of feet"
weather.info[["Description"]]["SKC"] <- "Sky Cover. CLR-Clear, SCT-Scattered-1/8to4/8, BKN-Broken-5/8to7/8, OBS-Obscured, POB-Partially Obscured"
weather.info[["Description"]]["L"] <- "Low Cloud Type"
weather.info[["Description"]]["M"] <- "Middle Cloud Type"
weather.info[["Description"]]["H"] <- "High Cloud Type"
weather.info[["Description"]]["VSB"] <- "Visibility in statute miles"
weather.info[["Description"]]["MW"] <- "Manually Observed Weather"
weather.info[["Description"]]["MW.1"] <- "Manually Observed Weather"
weather.info[["Description"]]["MW.2"] <- "Manually Observed Weather"
weather.info[["Description"]]["MW.3"] <- "Manually Observed Weather"
weather.info[["Description"]]["AW"] <- "Automatically Observed Weather"
weather.info[["Description"]]["AW.1"] <- "Automatically Observed Weather"
weather.info[["Description"]]["AW.2"] <- "Automatically Observed Weather"
weather.info[["Description"]]["AW.3"] <- "Automatically Observed Weather"
weather.info[["Description"]]["W"] <- "Past Weather Indicator"
weather.info[["Description"]]["TEMP"] <- "Temperature in degrees F"
weather.info[["Description"]]["DEWP"] <- "Dewpoint in degrees F"
weather.info[["Description"]]["SLP"] <- "Sea Level Pressure in millibars"
weather.info[["Description"]]["ALT"] <- "Altimeter setting in inches"
weather.info[["Description"]]["STP"] <- "Station pressure in millibars"
weather.info[["Description"]]["MAX"] <- "Max temp in degrees F"
weather.info[["Description"]]["MIN"] <- "Min temp in degrees F"
weather.info[["Description"]]["PCP01"] <- "1-hour liquid precipitation in inches"
weather.info[["Description"]]["PCP06"] <- "6-hour liquid precipitation in inches"
weather.info[["Description"]]["PCP24"] <- "24-hour liquid precipitation in inches"
weather.info[["Description"]]["PCPXX"] <- "3-hour liquid precipitation in inches"
weather.info[["Description"]]["SD"] <- "Snow Depth in Inches"